name = lmmi_01
description = A layout demonstrating the off canvas responsive navigation pattern.
preview = preview.png
template = lmmi_01-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/lmmi_01/lmmi_01.layout.css

; Scripts
scripts[] = layouts/lmmi_01/assets/lmmi_01.js
