name = Main layout for LMMI
description = modified version of omega offcanvas layout
preview = preview.png
template = lmmi-main-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
//stylesheets[all][] = css/layouts/lmmi-main/lmmi-main.layout.css
//stylesheets[all][] = dist/assets/css/lmmi-main.layout.css

; Scripts
scripts[] = layouts/lmmi-main/assets/off-canvas.js
